#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

event_actions('nethserver-dc-update', qw(
   initialize-default-databases 00
   nethserver-dc-fixchroot 40
   nethserver-dc-firststart 95
   nethserver-dc-machine-grants 96
));

event_templates('nethserver-dc-update', '/etc/sysconfig/nsdc');

event_actions('nethserver-dc-save', qw(
   nethserver-dc-create-bridge 01
   nethserver-dc-install 02
   nethserver-dc-provision 10
   nethserver-dc-waitstart 95
   nethserver-dc-join 96
   nethserver-dc-password-policy 97
   nethserver-dc-set-upn 97
   nethserver-dc-createadmins 98
   nethserver-dc-machine-grants 98
));

my @templates = (qw(
   /var/lib/machines/nsdc/etc/systemd/network/green.network
   /var/lib/machines/nsdc/etc/hostname
   /var/lib/machines/nsdc/etc/samba/smb.conf.include
   /var/lib/machines/nsdc/etc/hosts
   /var/lib/machines/nsdc/etc/resolv.conf
   /var/lib/machines/nsdc/etc/ntp.conf
   /var/lib/machines/nsdc/etc/systemd/system/samba-provision.service
   /var/lib/machines/nsdc/srv/smb.ns6upgrade.conf
   /etc/sysconfig/nsdc
   /etc/hosts
));

event_templates('nethserver-dc-save', @templates);

event_services('nethserver-dc-save', qw(
   nsdc restart
   dnsmasq restart
));

#backup
event_link("nethserver-dc-pre-backup" , "pre-backup-config", "40");
event_link("nethserver-dc-post-backup", "post-backup-config", "40");
event_link("nethserver-dc-pre-restore", "pre-restore-config", "40");
event_actions('post-restore-config', qw(
    nethserver-dc-install 01
    nethserver-dc-post-restore 40
));
event_templates('post-restore-config', @templates);


event_actions('interface-update', qw(
    nethserver-dc-condrestart 71
));
event_services('interface-update', qw(
    nsdc start
));

#--------------------------------------------------
# actions for user-create
#--------------------------------------------------
event_actions('user-create', qw(
    nethserver-dc-user-create 40
    nethserver-dc-sync-upn 50
));

#--------------------------------------------------
# actions for user-delete
#--------------------------------------------------
event_link("nethserver-dc-user-delete", "user-delete", "40");

#--------------------------------------------------
# actions for user-modify
#--------------------------------------------------
event_link("nethserver-dc-user-modify", "user-modify", "40");

#--------------------------------------------------
# actions for user-lock event
#--------------------------------------------------
event_actions('user-lock', qw(
              nethserver-dc-user-lock 15
));


#--------------------------------------------------
# actions for user-lock event
#--------------------------------------------------
event_actions('user-unlock', qw(
              nethserver-dc-user-unlock 15
));

# Update user settings when password policy changes:
event_actions('password-policy-update',
              'nethserver-dc-password-policy' => '30');

#--------------------------------------------------
# password-modify event
#--------------------------------------------------
event_actions('password-modify', qw(
              nethserver-dc-password-set 30
              nethserver-dc-user-unlock 40
));

#--------------------------------------------------
# actions for group-create
#--------------------------------------------------
event_link("nethserver-dc-group-create", "group-create", "40");

#--------------------------------------------------
# actions for group-delete
#--------------------------------------------------
event_link("nethserver-dc-group-delete", "group-delete", "40");

#--------------------------------------------------
# actions for group-modify
#--------------------------------------------------
event_link("nethserver-dc-group-modify", "group-modify", "40");

#
# migration-import event
#
event_actions('migration-import', qw(
      nethserver-dc-migrate 25
));

#
# nethserver-dc-factory-reset event
#
event_actions('nethserver-dc-factory-reset', qw(
    nethserver-dc-factory-reset 30
));

#
# nethserver-dc-upgrade event
#
event_templates('nethserver-dc-upgrade', qw(
    /var/lib/machines/nsdc/etc/samba/smb.conf.include
));
event_actions('nethserver-dc-upgrade', qw(
    nethserver-dc-fixinclude 20
    nethserver-dc-upgrade 30
));

# nethserver-dc-change-ip event
#
event_actions('nethserver-dc-change-ip', qw(
    nethserver-dc-change-ip 30
));
