#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

event_actions('nethserver-dc-update', qw(
   initialize-default-databases 00
   nethserver-dc-install 20
));

event_templates('nethserver-dc-save', qw(
   /etc/dnsmasq.conf
   /var/lib/machines/nsdc/etc/systemd/network/green.network
   /var/lib/machines/nsdc/etc/hostname
   /var/lib/machines/nsdc/etc/hosts
   /var/lib/machines/nsdc/etc/resolv.conf
   /var/lib/machines/nsdc/etc/sysconfig/samba-provision
   /etc/sysconfig/nsdc
));

event_services('nethserver-dc-save', qw(
   nsdc restart
   dnsmasq restart
));
