#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

event_actions('nethserver-dc-update', qw(
   initialize-default-databases 00
));


event_templates('nethserver-dc-update', qw(
    /etc/sudoers
));

event_actions('nethserver-dc-save', qw(
   nethserver-dc-install 20
   nethserver-dc-password-policy       50
));

event_templates('nethserver-dc-save', qw(
   /etc/dnsmasq.conf
   /var/lib/machines/nsdc/etc/systemd/network/green.network
   /var/lib/machines/nsdc/etc/hostname
   /var/lib/machines/nsdc/etc/hosts
   /var/lib/machines/nsdc/etc/resolv.conf
   /var/lib/machines/nsdc/etc/sysconfig/samba-provision
   /etc/sysconfig/nsdc
));

event_services('nethserver-dc-save', qw(
   nsdc restart
   dnsmasq restart
));

#backup
event_link("nethserver-dc-pre-backup" , "pre-backup-config", "40");
event_link("nethserver-dc-post-backup", "post-backup-config", "40");
event_link("nethserver-dc-pre-restore", "pre-restore-config", "40");
event_link("nethserver-dc-post-restore", "post-restore-config", "40");

#--------------------------------------------------
# actions for user-create
#--------------------------------------------------
event_link("nethserver-dc-user-create", "user-create", "40");

#--------------------------------------------------
# actions for user-delete
#--------------------------------------------------
event_link("nethserver-dc-user-delete", "user-delete", "40");

#--------------------------------------------------
# actions for user-modify
#--------------------------------------------------
event_link("nethserver-dc-user-modify", "user-modify", "40");

#--------------------------------------------------
# actions for user-lock event
#--------------------------------------------------
event_actions('user-lock', qw(
              nethserver-dc-user-lock 15
));


#--------------------------------------------------
# actions for user-lock event
#--------------------------------------------------
event_actions('user-unlock', qw(
              nethserver-dc-user-unlock 15
));

# Update user settings when password policy changes:
event_actions('password-policy-update',
              'nethserver-dc-password-policy' => '30');

#--------------------------------------------------
# password-modify event
#--------------------------------------------------
event_actions('password-modify', qw(
              nethserver-dc-password-set 30
              nethserver-dc-user-unlock 40
));

#--------------------------------------------------
# actions for group-create
#--------------------------------------------------
event_link("nethserver-dc-group-create", "group-create", "40");

#--------------------------------------------------
# actions for group-delete
#--------------------------------------------------
event_link("nethserver-dc-group-delete", "group-delete", "40");

#--------------------------------------------------
# actions for group-modify
#--------------------------------------------------
event_link("nethserver-dc-group-modify", "group-modify", "40");


validator_actions('dcipaddr', qw(
    ipgreenandbridged 20
));

#--------------------------------------------------
# Create bridge on save
#--------------------------------------------------
event_link("nethserver-dc-create-bridge", "nethserver-dc-save","02");

