#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use JSON;

my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $domain = $db->get_value('DomainName');
my $expression;
my $attributes;
my $cmd;


#
# Get groups and members
#

$expression = '(objectCategory=group)';
$attributes = 'sAMAccountName member';
$cmd = '/usr/bin/net ads search -P ';
$cmd .= " '$expression' ";
$cmd .= " $attributes ";

open(PS,$cmd.'|');

my %groups;
my $group = '';

while ( <PS> ){
    if ($_ ~~ /^sAMAccountName:\s+(.*)$/){
        $group = lc($1).'@'.$domain;
        $groups{$group}{'members'} = [];
    } elsif ($_ ~~ /^member: CN=([^,]*),.*/){
       #add member
       push($groups{$group}{'members'}, lc($1).'@'.$domain);
    }
}

print to_json(\%groups);


exit 0;
