#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use JSON;

my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $domain = $db->get_value('DomainName');
my $expression;
my $attributes;
my $cmd;


$expression = '(&(objectCategory=user)(!(sAMAccountName=krbtgt))(!(sAMAccountName=Guest)))';
$attributes = 'sAMAccountName cn userAccountControl accountExpires memberOf pwdLastSet loginShell displayName';
$cmd = '/usr/bin/net ads search -P ';
$cmd .= " '$expression' ";
$cmd .= " $attributes ";

my %users = ();
my $cn;
my $displayName;
my $username;
my $userAccountControl;
my $accountExpires;
my @groups;
my $pwdLastSet;
my $loginShell = "/usr/libexec/openssh/sftp-server";
my @sysgroups = ("Allowed RODC Password Replication Group","Enterprise Read-Only Domain Controllers","Denied RODC Password Replication Group","Pre-Windows 2000 Compatible Access","Windows Authorization Access Group","Certificate Service DCOM Access","Network Configuration Operators","Terminal Server License Servers","Incoming Forest Trust Builders","Read-Only Domain Controllers","Group Policy Creator Owners","Performance Monitor Users","Cryptographic Operators","Distributed COM Users","Performance Log Users","Remote Desktop Users","Account Operators","Event Log Readers","RAS and IAS Servers","Backup Operators","Domain Controllers","Server Operators","Enterprise Admins","Print Operators","Administrators","Domain Computers","Cert Publishers","DnsUpdateProxy","Domain Admins","Domain Guests","Schema Admins","Domain Users","Replicator","IIS_IUSRS","DnsAdmins","Guests","Users");

sub saveUser {
    if ($userAccountControl eq '514' || $userAccountControl eq '66050') {
        $users{$username}{'locked'} = 1;
    } else {
        $users{$username}{'locked'} = 0;
    }
    $users{$username}{'gecos'} = $displayName || $cn;

    #check if user expires and if it's expired
    $users{$username}{'expired'} = 0;
    if (( $userAccountControl eq '512' || $userAccountControl eq '514' || $userAccountControl eq '544' || $userAccountControl eq '546' || $userAccountControl eq '262656' || $userAccountControl eq '262658' || $userAccountControl eq '262688' || $userAccountControl eq '262690' )) {
        $users{$username}{'expires'} = 'yes';
        if ($accountExpires/10000000-11644473600 < time()){
            $users{$username}{'expired'} = 1;
        } 
    } else {
        $users{$username}{'expires'} = 'no';
    }

    $users{$username}{'groups'} = [];
    push ($users{$username}{'groups'}, @groups);
    @groups = ();
    if ($pwdLastSet eq '0'){
        $users{$username}{'new'} = 1;
    } else {
        $users{$username}{'new'} = 0;
    }
    $users{$username}{'shell'} = $loginShell;
    $loginShell = "/usr/libexec/openssh/sftp-server";
}

open(PS,$cmd.'|');
while ( <PS> ){
    if ($_ ~~ /^cn: (.*)$/){
        if ($cn){
            # new user! save previous one
            saveUser();
        }
        $cn = $1;
    } elsif ($_ ~~ /^displayName:\s+(.*)$/){
        $displayName = $1;
    } elsif ($_ ~~ /^sAMAccountName:\s+(.*)$/){
        $username = lc($1).'@'.$domain;
    } elsif ($_ ~~ /^accountExpires:\s+(.*)$/){
        $accountExpires = $1;
    } elsif ($_ ~~ /^userAccountControl:\s+(.*)$/){
        $userAccountControl = $1;
    } elsif ($_ ~~ /^memberOf:\s+CN=([^,]*),.*$/){
        #add group to group list if isn't in system group list
        if (!grep( /^$1$/, @sysgroups)){
            push (@groups, $1.'@'.$domain);
        }
    } elsif ($_ ~~ /^pwdLastSet:\s+(.*)$/){
        $pwdLastSet = $1;
    } elsif ($_ ~~ /^loginShell:\s+(.*)$/){
        $loginShell = $1;        
    } 
}

#write last user to users array
saveUser();

print to_json(\%users);

exit 0;
