#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

event=$1
errors=0

function count_errors ()
{
    (( errors ++ ))
}

trap count_errors ERR

/sbin/e-smith/config setprop sssd Provider none status disabled AdDns ''
/sbin/e-smith/signal-event nethserver-sssd-leave
/sbin/e-smith/signal-event nethserver-dnsmasq-save

if systemctl -q is-active nsdc; then
    systemctl stop nsdc
fi

if systemctl -q is-enabled nsdc; then
    systemctl disable nsdc
fi

rm -vf /var/lib/machines/nsdc/etc/samba/smb.conf
find /var/lib/machines/nsdc/var/lib/samba/ -type f | xargs -- rm -vf

/sbin/e-smith/config setprop nsdc status disabled IpAddress ''

exit $errors
