#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::db;
use esmith::ConfigDB;
use Errno;
use English;

my $event = shift;
my $userName = shift;

if( ! $userName ) {
    warn("[ERROR] Missing username argument");
    exit(1);
}

my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $passwd = esmith::db->open("NethServer::Database::Passwd") || die("Could not open Passwd DB");


# Handle users with and without domain part
my $account = undef;
if ($userName =~ /@/) {
    $account = $passwd->get($userName);
    $userName = (split(/@/,$userName))[0];
} else {
    my $domain = $db->get_value('DomainName');
    $account = $passwd->get($userName.'@'.$domain);
}
if( ! $account) {
    die "[ERROR] Account `$userName` not found.\n";
}

my $cmd = "/usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool user enable '$userName'" ;

system($cmd) == 0
        or die "Error running samba-tool command to unlock account $userName";

# Check if the user is really unlocked
my $out = `/usr/bin/systemd-run -M nsdc -q -t pdbedit -L -w $userName | cut -d: -f5 `;
if ($out =~ /D/) {
    exit 1;
} 

exit 0;


