#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# Add alternate UPN suffix
BaseDN=$(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->baseDN();')
Domain=$(hostname -d)

# Generate temporary files and configure cleanup handler
nsdc_prefix=/var/lib/machines/nsdc
tmp_ldif=$(mktemp -p ${nsdc_prefix}/var/spool upn-XXXXXX.ldif)
trap "rm -f ${tmp_ldif}" EXIT

echo "dn: cn=Partitions,cn=Configuration,$BaseDN
changetype: modify
replace: uPNSuffixes
uPNSuffixes: ${Domain}
" > ${tmp_ldif}

systemd-run -M nsdc -q -t ldbmodify -v -i -H /var/lib/samba/private/sam.ldb ${tmp_ldif#${nsdc_prefix}} | \
    grep -q -F 'Modified 1 records successfully'
if [[ $? != 0 ]]; then
    echo "[ERROR] UPN suffix update failed"
fi
