#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use NethServer::SSSD; 

my $event = shift;
my $userName = shift;
my $FullName = shift;
my $shell = shift || '/usr/libexec/openssh/sftp-server';

my $sssd = new NethServer::SSSD();
my $baseDN = $sssd->baseDN();

if(! defined ($userName)) {
    die "Username argument missing\n";
}

#accept user@domain format
$userName =~ s/@.*//;

#Modify user FullName
system(qq(expect -c 'spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/pdbedit -u "$userName" "--fullname=$FullName"; expect "Unix username:" { exit 0 }; exit 3' >/dev/null));
if ($? != 0) {
    die("[ERROR] User $userName modification failed\n");
}


#Create a ldif file and use it to modify the shell access
#a random name and a chmod is done for security
my $path = '/var/lib/machines/nsdc/var/lib/samba/private/';
my $fileName = "$userName-". sprintf("%08X", rand(0xFFFFFFFF)).".ldif";
my $filePath = $path . $fileName;

my $contentFile = qq (
dn: cn=$userName,cn=Users,$baseDN
changetype: modify
replace: loginShell
loginShell: $shell
);

open(my $fh, '>', $filePath) or die "Could not open file '$filePath' $!";
chmod 0600, $filePath;
print $fh $contentFile;
close $fh;

#Launch ldbmodify and expect the return
system(qq(expect -c 'spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/ldbmodify -H /var/lib/samba/private/sam.ldb /var/lib/samba/private/$fileName;
    expect "Modified 1 records successfully" { exit 0 }; exit 3' >/dev/null));

if ($? != 0) {
    die("[ERROR] User $userName shell modification failed\n");
}

unlink $filePath;
