#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

nsroot=/var/lib/machines/nsdc

if ! [ -d ${nsroot} ]; then
    mkdir -p ${nsroot}/etc/yum/vars
    cp -vf /etc/yum/vars/distroversion ${nsroot}/etc/yum/vars/distroversion
    yum -y --releasever=7 --installroot=${nsroot} install ns-samba centos-release systemd-networkd
    systemctl enable machines.target
fi

