#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

event=$1
nsroot=/var/lib/machines/nsdc

if [[ ! -x ${nsroot}/usr/sbin/samba ]]; then
    echo "[WARNING] nsdc containter not installed. Skipping the update"
    exit 0
fi

# Synchronize YUM configuration
rsync -ai --delete /etc/yum.repos.d/ ${nsroot}/etc/yum.repos.d
rsync -ai --delete /etc/yum/vars/ ${nsroot}/etc/yum/vars

# Upgrade chroot base system & samba package
yum -y --releasever=/ --installroot=${nsroot} update \* /usr/lib/nethserver-dc/ns-samba-*.ns7.x86_64.rpm -y | /usr/libexec/nethserver/ptrack-nsdc-install

if [[ $? != 0 ]]; then
    echo "[ERROR] Failed to update the nsdc chroot"
    exit 1
fi

# Workaround to BZ#1431198 krb5-libs-1.15.1-13 (includedir fix, not supported by Heimdal Kerberos)
cp -vfp ${nsroot}/var/lib/samba/private/krb5.conf ${nsroot}/etc/krb5.conf

# Restart the Samba DC service in nsdc container
systemctl -M nsdc restart samba
