#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use esmith::db;
use File::Path;
use NethServer::Database::Passwd;
use NethServer::SSSD;
use esmith::ConfigDB;

my $conf = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $sssd = new NethServer::SSSD();

my $passwd = esmith::db->open("NethServer::Database::Passwd") || die("Could not open Passwd DB");
my $homeDirPrefix = '/var/lib/nethserver/home/';

my $event = shift;
my $groupName = shift;

if(! defined ($groupName)) {
    die "Group name argument missing\n";
}

#Delete group 
my $out = `/usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool group delete "$groupName"`;

#die if group output differs from successful output
if ($out !~ /^Deleted group /){
    die $out."\n";
}

print "$out";
