#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

provider=$(/sbin/e-smith/config getprop sssd Provider)

if [[ "${provider}" != "ad" ]]; then
    exit 0
fi

nsroot=/var/lib/machines/nsdc

for package in bind-utils ntp
do
    if ! rpm -q --root=${nsroot} $package >/dev/null; then
        echo "[NOTICE] Fixing nsdc chroot, by installing $package package"
        yum -y --releasever=/ --installroot=${nsroot} install $package | /usr/libexec/nethserver/ptrack-nsdc-install
    fi
done

# Enable ntpd service
if ! systemctl --quiet -M nsdc is-active ntpd; then
    systemctl -M nsdc enable ntpd
fi

# Set ntpd permissions
uid=$(grep ntp ${nsroot}/etc/passwd | awk -F: '{print $3}')
chown 0:$uid ${nsroot}/var/lib/samba/ntp_signd/
chmod 750 ${nsroot}/var/lib/samba/ntp_signd/

