#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;

my $event = shift;
my $groupName = shift;

if(! defined ($groupName)) {
    die "Group name argument missing\n";
}

#accept group@domain format
$groupName =~ s/@.*//;

#Create group 
system(qq(expect -c 'spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool group add "$groupName"; expect "Added group" { exit 0 }; exit 3'));
if ($? != 0) {
    die("[ERROR] Group $groupName creation failed\n");
}

#Add members to group 
my $members = join(',', @ARGV);
if($members) {
    system(qq(expect -c 'spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool group addmembers "$groupName" "$members"; expect "Added members" { exit 0 }; exit 3'));
    if ($? != 0) {
        die("[ERROR] Failed to add members to group $groupName\n");
    }
}
