#!/usr/bin/perl -w 

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use File::Temp;

my $event = shift;
my $userName = shift;
my $FullName = shift;
my $shell = shift || '/usr/libexec/openssh/sftp-server';

if(! defined ($userName)) {
    die "Username argument missing\n";
}

#accept user@domain format
$userName =~ s/@.*//;

#Modify user FullName
system(qq(expect -c 'spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/pdbedit -u "$userName" "--fullname=$FullName"; expect "Unix username:" { exit 0 }; exit 3' >/dev/null));
if ($? != 0) {
    die("[ERROR] User $userName modification failed\n");
}

#Create a temporary ldif file (root:root 0600)
my $fileFullPath = File::Temp->new(
    TEMPLATE => "$userName.XXXXXXXXXX",
    DIR => '/var/lib/machines/nsdc/var/spool/'
);

#retrieve the dn from samaccountname
my $dn = qx(systemd-run -M nsdc -q -t /usr/bin/ldbsearch -H /var/lib/samba/private/sam.ldb "samaccountname=$userName" dn | sed -n '/^dn: / { s/\r// ; p ; q }');
chomp $dn;

#print the content
print $fileFullPath qq (
$dn
changetype: modify
replace: loginShell
loginShell: $shell
);

close($fileFullPath);

#we need the relative path in the container
my $fileRelativePath = $fileFullPath; 
$fileRelativePath =~ s|/var/lib/machines/nsdc||;

#modif the samba LDAP
system(qq(expect -c 'spawn -noecho /usr/bin/systemd-run -M nsdc -q -t /usr/bin/ldbmodify -H /var/lib/samba/private/sam.ldb $fileRelativePath;
    expect "Modified 1 records successfully" { exit 0 }; exit 3' >/dev/null));

if ($? != 0) {
    die("[ERROR] User $userName shell modification failed\n");
}
