#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# Add alternate UPN suffix
BaseDN=$(perl -MNethServer::SSSD -e 'print NethServer::SSSD->new()->baseDN();')
LdapUri=$(php -r 'echo urlencode(trim($argv[1]));' -- ${BaseDN})
KrbRealm=$(/sbin/e-smith/config getprop sssd Realm)
Domain=$(hostname -d)
Password='Nethesis,1234'

ldapmodify -D Administrator@$KrbRealm -w $Password -H "ldap:///${LdapUri}" <<EOF
dn: cn=Partitions,cn=Configuration,$BaseDN
changetype: modify
replace: uPNSuffixes
uPNSuffixes: $Domain
EOF

if [[ $? != 0 ]]; then
    echo "[ERROR] UPN suffix update failed (LdapUri ${LdapUri})"
fi

