#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

if ! [ $# -ge 3 ]; then
   echo "[ERROR] Not enough arguments."
   exit 2
fi

EVENT=$1
USER=$2
FILE=$3
DOMAIN=$(hostname -d)

if ! [[ $USER == *"@${DOMAIN}" ]]; then
    echo "[NOTICE] Skipping user ${USER}, it doesn't belong to our domain."
    exit 0
fi

if ! [ -f "${FILE}" ]; then
    echo "[ERROR] Password file not found"
    exit 1
fi

exec expect -f - >/dev/null <<EOF
spawn /usr/bin/nsdc-cmd -r /usr/bin/samba-tool user setpassword "${USER%@${DOMAIN}}"
log_user 1
expect {
    -ex "New Password: " {
         send -- [read -nonewline [open "${FILE}" r]]
         send "\n"
         expect {
            "Changed password OK" {
               exit 0
            }
            -ex "Retype Password: " {
                send -- [read -nonewline [open "${FILE}" r]]
                send "\n"
                expect {
                    "Changed password OK" {
                        exit 0
                    }
                }
            }
            timeout {exit 3}
            eof {exit 2}
         }
    }
}
EOF

