#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

nsroot=/var/lib/machines/nsdc

if ! [ -d ${nsroot}/etc/yum/vars ]; then
    mkdir -p ${nsroot}/etc/yum/vars
    mkdir -p ${nsroot}/var/log/journal
    mkdir -p ${nsroot}/etc/systemd/network
    yum -y --releasever=7 --installroot=${nsroot} install /usr/lib/nethserver-dc/ns-samba-*.ns7.x86_64.rpm centos-release systemd-networkd | /usr/libexec/nethserver/ptrack-nsdc-install
    systemctl enable machines.target
    systemctl --root=${nsroot} enable samba-provision.service samba.service
fi
