#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Revoke Account Operator privilege to the local machine account (#5396)

# Run only if we are a local accounts provider:
perl -MNethServer::SSSD -e 'exit(NethServer::SSSD->new()->isLocalProvider() ? 0 : 1);'
if [[ $? != 0 ]]; then
    exit 0
fi

sAMAccountName=$(hostname -s | cut --bytes=-15 | tr '[:lower:]' '[:upper:]')\$

/usr/bin/nsdc-cmd /usr/bin/samba-tool group listmembers \'Account Operators\' | grep -q -F "${sAMAccountName}"

if [[ $? == 0 ]]; then
    /usr/bin/nsdc-cmd  /usr/bin/samba-tool group removemembers \'Account Operators\' \'${sAMAccountName}\'
    if [[ $? == 0 ]]; then
        echo "[NOTICE] Removed machine account from Account Operators group"
    fi
fi
