#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use File::Path;

my $homeDirPrefix = '/var/lib/nethserver/home/';

my $event = shift;
my $userName = shift;
my $FullName = shift || '';
my $shell = shift || '/usr/libexec/openssh/sftp-server';

if(! defined ($userName)) {
    die "Username argument missing\n";
}

if( ! -x $shell) {
    warn "Given shell `$shell` is not executable";
    $shell = '/bin/false';
}

if ($FullName eq '') {
    $FullName = $userName;
}

#accept user@domain format
$userName =~ s/@.*//;

#Create user
system(qw(nsdc-run -e -- /usr/bin/samba-tool user create), $userName, '--random-password', '--must-change-at-next-login', "--login-shell=$shell", "--unix-home=${homeDirPrefix}${userName}", "--given-name=$FullName", '--use-username-as-cn');
if ($? != 0) {
    die("[ERROR] User $userName creation failed\n");
}

