#!/bin/bash

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

nsroot=/var/lib/machines/nsdc

nsdc-run -e -- /usr/bin/bash -c '
function get_dn()
{
  /usr/bin/ldbsearch -H /var/lib/samba/private/sam.ldb "sAMAccountName=$1" dn | \
    sed -n "/^dn: / { s/\r// ; p ; q }"
}

DN=$(get_dn ldapservice)

/usr/bin/ldbmodify -v -i -H /var/lib/samba/private/sam.ldb <<EOF
${DN}
changetype: modify
replace: userWorkstations
EOF
'

exit 0
