#!/bin/bash

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

for DB in $(find /var/lib/machines/nsdc/var/lib/samba/ -name "*.[t,l]db"); do
    RELATIVE=$(echo $DB | sed 's/^\/var\/lib\/machines\/nsdc//')
    /usr/bin/systemd-run -M nsdc -t -q /usr/bin/tdbbackup "$RELATIVE"
    if [ ! -f ${DB}.bak ]; then
        echo "Error while backing up ${DB}!"
        exit 1
    fi
done
