#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

if ! [ $# -ge 3 ]; then
   echo "[ERROR] Not enough arguments."
   exit 2
fi

EVENT=$1
USER=$2
FILE=$3

if ! [[ $USER == *"@"* ]]; then
    echo "[WARN] Skipping user $USER, it doesn't belong to a domain."
    exit 0
else
    USER=`echo $USER| cut -d@ -f1`
fi

if ! [ -f "${FILE}" ]; then
    echo "[ERROR] Password file not found"
    exit 1
fi

PASSWORD=`cat $FILE`
out=`/usr/bin/systemd-run -M nsdc -q -t /usr/bin/samba-tool user setpassword --newpassword='$PASSWORD' $USER`

echo $out | grep -q "Changed password OK"
if [ $? -gt 0 ]; then
    echo $out
    exit 1
fi

exit 0
