#!/usr/bin/perl -w

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use File::Path qw(remove_tree);

my $event = shift;
my $userName = shift;

if(! defined ($userName)) {
    die "Username argument missing\n";
}

#accept user@domain format
$userName =~ s/@.*//;

# Remove home
if ( -d "/var/lib/nethserver/home/$userName") {
    remove_tree ("/var/lib/nethserver/home/$userName") ||
        die "[ERROR] The home of $userName cannot be removed: $?";
}
