#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use Locale::TextDomain ('nethserver-dc');
use JSON;

my $cdb = esmith::ConfigDB->open_ro() || die("Could not open ConfigDB");
my $provider = $cdb->get_prop("sssd", "Provider") || '';
my $response = undef;

if($provider eq 'none') {
    $response = {
        'action' => {
            'label' => __('Configure Samba Active Directory'),
            'url' => '/Account'
        },
        'text' => __('The Domain Controller (DC) container must be configured before being started'),
        'icon' => 'edit'
    };
}

if(defined $response) {
    print encode_json($response);
}
