#!/usr/bin/python

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import gettext
import json
import sys
import re
import subprocess

try:
    p = subprocess.Popen(['/sbin/e-smith/config', 'getprop', 'nsdc', 'IpAddress'], stdout=subprocess.PIPE)
    ip, err = p.communicate()
except:	
    exit(1)

if(ip.rstrip() == ''):
    gettext.textdomain('nethserver-dc')
    msg = {
        "action": {
            "label": gettext.gettext('Configure Samba 4 IP'),
            "url": '/DomainController'
        },
        "text": gettext.gettext('Configure an IP address for Samba 4 Domin Controller virtual machine'),
        "icon": "edit"
    }
    json.dump(msg, sys.stdout)
