#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;

my $nsdcIp = shift;

use esmith::NetworksDB;
use Net::IPv4Addr qw( :all );
my $ndb = esmith::NetworksDB->open_ro();

my @greens = $ndb->green();

my $error = 3; # no green bridge found

foreach (@greens) {
    my $type = $_->prop('type') || 'ethernet';
    if($type eq 'bridge') {
        $error = 4; # at least one green bridge was found
    }
    if ($type eq 'bridge' && ipv4_in_network($_->prop('ipaddr'), $_->prop('netmask'), $nsdcIp, '255.255.255.255')) {
        exit(0); # SUCCESS!
    }
}

exit($error);